Repository yjosp95/Project2, pull requests merged in 2020-05, with the labels that each got.

#25 main.c, 4번함수 5번함수
  main.c
Labels: Develop

#26 6번 함수 수정했습니다
  main.c
Labels: Develop

#27 Update : 7번, 8번 함수 추가
  main.c
Labels: Develop

#29 README.MD 작성했습니다
  README.md
Labels: documentation

#31 파일 1 파일 2 변동 있어서 Pull Request 합니다!
  text1
  text1.txt
  text2
  text2.txt
Labels: documentation

#34 파일 확장자 수정했습니다.
  main.c
Labels: Develop

#37 5번함수 수정
  main.c
Labels: update

#38 함수 6 수정했습니다
  main.c
Labels: update

#41 Update : Function 7, 8
  main.c
Labels: update
